Add initial schema for ovn-provider-controller.
Signed-off-by: Numan Siddique <numans@ovn.org>

diff --git a/tutorial/ovn-sandbox b/tutorial/ovn-sandbox
--- a/tutorial/ovn-sandbox
+++ b/tutorial/ovn-sandbox
@@ -64,6 +64,8 @@ gdb_ovn_controller=false
 gdb_ovn_controller_ex=false
 gdb_ovn_controller_vtep=false
 gdb_ovn_controller_vtep_ex=false
+gdb_ovn_pr_controller=false
+gdb_ovn_pr_controller_ex=false
 builddir=
 ovsbuilddir=
 srcdir=
@@ -90,6 +92,7 @@ ic_nb_servers=3
 ic_sb_model=clustered
 ic_sb_servers=3
 dummy=override
+ovn_pr=false
 
 for option; do
     # This option-parsing mechanism borrowed from a Autoconf-generated
@@ -339,6 +342,9 @@ EOF
         --ic-sb-m*)
             prev=ic_sb_model
             ;;
+        --ovn-pr)
+            ovn_pr=true
+            ;;
         -R|--gdb-run)
             gdb_vswitchd_ex=true
             gdb_ovsdb_ex=true
@@ -422,6 +428,11 @@ if $built; then
         echo >&2 'source directory not found, please use --srcdir'
         exit 1
     fi
+    pr_schema=$srcdir/ovn-pr.ovsschema
+    if test ! -e "$pr_schema"; then
+        echo >&2 'source directory not found, please use --srcdir'
+        exit 1
+    fi
 
     # Put built tools early in $PATH.
     if test ! -e $ovsbuilddir/vswitchd/ovs-vswitchd; then
@@ -429,7 +440,7 @@ if $built; then
         exit 1
     fi
     PATH=$ovsbuilddir/ovsdb:$ovsbuilddir/vswitchd:$ovsbuilddir/utilities:$ovsbuilddir/vtep:$PATH
-    PATH=$builddir/controller:$builddir/controller-vtep:$builddir/northd:$builddir/ic:$builddir/utilities:$PATH
+    PATH=$builddir/controller:$builddir/controller-vtep:$builddir/northd:$builddir/ic:$builddir/utilities:$builddir/pr-controller:$PATH
     export PATH
 else
     case $schema in
@@ -616,6 +627,10 @@ ovn_start_db sb "$sbdb_model" "$sbdb_servers" "$ovnsb_source"
 ovn_start_db ic_nb "$ic_nb_model" "$ic_nb_servers" "$ic_nb_schema"
 ovn_start_db ic_sb "$ic_sb_model" "$ic_sb_servers" "$ic_sb_schema"
 
+if $ovn_pr; then
+    ovn_start_db pr standalone 1 "$pr_schema"
+fi
+
 #Add a small delay to allow ovsdb-server to launch.
 sleep 0.1
 
@@ -692,6 +707,13 @@ rungdb $gdb_ovn_controller_vtep $gdb_ovn_controller_vtep_ex \
     $OVN_CTRLR_PKI --log-file -vsyslog:off \
     --ovnsb-db="$OVN_SB_DB"
 
+if $ovn_pr; then
+    run ovs-vsctl set open . external-ids:ovn-provider-remote=$OVN_PR_DB
+    rungdb $gdb_ovn_pr_controller $gdb_ovn_pr_controller_ex ovn-pr-controller \
+        --detach --no-chdir -vsyslog:off \
+        --log-file=ovn-pr-controller.log \
+        --pidfile=ovn-pr-controller.pid -vconsole:off
+fi
 cat <<EOF
 
 
